homework31/store/api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('games/', views.GameList.as_view()),
]

homework31/store/game_store/urls.py
from django.urls import path

from . import views


app_name = 'game'
urlpatterns = [
    path('', views.games_all, name='games'),
    path('category/', views.all_categories, name='all_categories'),
    path('sorting/', views.sorting, name='sorting'),
    path('category/<slug:category_slug>/', views.category_games, name='category_games'),
    path('search-games', views.search_games, name='search-games'),
    path('<slug:game_slug>/comment/', views.CommentCreateView.as_view(), name='comment_add'),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('<slug:game_slug>/', views.every_game, name='game_slug'),
]

homework31/store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game_store.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homework31/store/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'user'
urlpatterns = [
    path('login_user', views.login_user, name='login'),
    path('logout_user', views.logout_user, name='logout'),
    path('register_user', views.register_user, name='register_user'),
    path('change_pass/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_success', auth_views.PasswordResetDoneView.as_view(
                        template_name = 'authenticate/password_success.html'
                    ), name='password_success'),
]   

homework31/store/game_store/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'grade')
        labels = {
            'text': 'Комментарий',
            'grade': 'Оценка Игры',
        }
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Комментарий'}),
            'grade': forms.Select(attrs={'class': 'form-input'}),
        }

homework31/store/game_store/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Avg
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

import datetime   

from .models import Game, Category, Comment
from .forms import CommentForm


def games_all(request):
    """
    Функция представления игр у которых поле is_active=True.
    """

    games = Game.objects.filter(is_active=True).all()
    return render(request, 'games/home.html', {'games': games})


@login_required(login_url='user:login')
def every_game(request, game_slug):
    """
    Функция представления игры по slug полю.
    """

    game = get_object_or_404(Game, slug=game_slug)
    comments = game.comments.all().order_by('-pub_date')
    last = request.COOKIES.get(game_slug)
    average_grade = game.comments.aggregate(Avg('grade'))
    session_key = f'{game_slug}_visits'
    visits = request.session.get(session_key, 0)
    visits += 1
    request.session[session_key] = visits
    context = {
        'game': game,
        'comments': comments,
        'last': last,
        'visits': visits,
        'average_grade': average_grade['grade__avg'],
    }
    response = render(request, 'games/game.html', context=context)
    visit_time = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    response.set_cookie(game_slug, visit_time)
    return response


def all_categories(request):
    """
    Функция представления категории у которых поле is_active=True.
    """

    categories = Category.objects.filter(is_active=True)
    return render(request, 'category/all_categories.html', {'categories': categories})


@login_required(login_url='user:login')
def category_games(request, category_slug):
    """
    Функция представления игр каждой категории.
    """

    category = get_object_or_404(Category, slug=category_slug)
    games = category.game_set.filter(is_active=True, category=category)
    context = {
        'category': category,
        'games': games
    }
    return render(request, 'category/category_games.html', context)


def sorting(request):
    """
    Функция представления, сортировки игр.                      
    """
    sort = request.GET.get('sort')  
    sort_order = {
        'name_desc': Game.objects.order_by('-name'),
        'name_asc': Game.objects.order_by('name'),
    }
    games = sort_order.get(sort)
    return render(request, 'sorting/sorting.html', {'games': games})


def search_games(request):
    """
    Поиск игры по имени.
    """

    if request.method == 'POST':
        searched = request.POST['searched']
        games = Game.objects.filter(name__icontains=searched)
        return render(request, 'search/search_games.html', {'searched': searched, 'games': games})
    else:
        return render(request, 'search/search_games.html', {})


class CommentCreateView(CreateView, LoginRequiredMixin):
    """
    Добавление комментария в игру пользователем.
    """

    template_name = 'comments/comment_create.html'
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.game = Game.objects.get(slug=self.kwargs['game_slug'])
        return super().form_valid(form)


class CommentUpdateView(UpdateView):
    """
    Редактирование комментария в игре.
    """

    model = Comment
    template_name = 'comments/comment_update.html'
    form_class = CommentForm


class CommentDeleteView(DeleteView):
    """
    Удаление комментария в игре.
    """

    model = Comment
    template_name = 'comments/comment_delete.html'
    success_url = reverse_lazy('game:games')

homework31/store/game_store/templates/game_store/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
            crossorigin="anonymous"
        >
        <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"
        ></script>
<style>
body {
    background: #1f2d3b;
    color: #8694a4;
    margin: 0;
}
</style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'game:games' %}">Games</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'game:all_categories' %}">Categories</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Sorting
                    </a>
                        <ul class="dropdown-menu bg-info-subtle">
                            <li><a class="dropdown-item " href="{% url 'game:sorting'%}?sort=name_asc">Sorting A-Z</a></li>
                            <li><a class="dropdown-item" href="{% url 'game:sorting'%}?sort=name_desc">Sorting Z-A</a></li>
                        </ul>
                </li>
            </ul>
            <form class="d-flex me-lg-4" method="post" action="{% url 'game:search-games' %}">
                {% csrf_token %}
                <input class="form-control me-2 bg-info-subtle" type="search" 
                placeholder="Search Games" aria-label="Search" name="searched">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <ul class="navbar-nav me-5">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#"  data-bs-toggle="dropdown" >
                            User: {{user.username.capitalize}}
                        </a>
                        <ul class="dropdown-menu bg-info-subtle ">
                            <li><a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
                            <li><a class="dropdown-item" href="{% url 'user:password_change' %}">Password Change</a>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                    <a class="nav-link "href="{% url 'user:register_user' %}">Register</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link "href="{% url 'user:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
            </div>
        </div>
    </nav>
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
</div>
{% block content %}
{% endblock %}
{% include 'game_store/footer.html'%}
</body>
</html>

homework31/store/game_store/templates/game_store/footer.html
<footer class="container-fluid text-center p-2 mt-5 ">
    <hr>
    <p>&copy; Game Store {% now 'Y' %} || Copyright || Developer: Alex Alashnikov</p>
</footer>