homework23/store/game_store/urls.py
from django.urls import path

from . import views

app_name = 'game'
urlpatterns = [
    path('', views.games_all, name='games'),
    path('category/', views.all_categories, name='all_categories'),
    path('<slug:game_slug>/', views.every_game, name='game_slug'),
    path('category/<slug:category_slug>/', views.category_games, name='category_games'),
]

homework23/store/game_store/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField('Жанр', max_length=20)
    slug = models.SlugField('Ярлык Категории', max_length=25)
    description = models.TextField('Описание Категории')
    is_active = models.BooleanField('Категория Доступна')

    def __str__(self):
        return f'{self.title}'


class Game(models.Model):
    name = models.CharField('Название Игры', max_length=50)
    pub_date = models.DateField('Дата Публикации', auto_now_add=True)
    release_date = models.DateField('Дата Выхода')
    price = models.DecimalField('Цена', max_digits=5, decimal_places=2)
    slug = models.SlugField('Ярлык Игры', max_length=35)
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default=None)
    description = models.TextField('Описание Игры')
    game_image = models.ImageField('Изображение Игры', upload_to='game_store/media/games')
    is_active = models.BooleanField('Игра Доступна')

    def __str__(self):
        return f'{self.name}'

homework23/store/game_store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Game, Category


def every_game(request, game_slug):
    game = get_object_or_404(Game, slug=game_slug)
    return render(request, 'games/game.html', {'game': game})


def games_all(request):
    games = Game.objects.filter(is_active=True).all()
    return render(request, 'games/home.html', {'games': games})


def category_games(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    games = Game.objects.filter(is_active=True, category=category)
    context = {
        'category': category,
        'games': games
    }
    return render(request, 'category/category_games.html', context)


def all_categories(request):
    categories = Category.objects.filter(is_active=True)
    return render(request, 'category/all_categories.html', {'categories': categories})

homework23/store/game_store/templates/category/all_categories.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Categories{% endblock %}

{% block content %}
<code>
{% for category in categories %}
<div class="container text-center my-5">
    <h1 class="fw-light"><a href="{% url 'game:category_games' category_slug=category.slug %}">{{category.title}}</a></h1>
    <br><br>
    <div class="row">
        <div class="col-lg-6 col-md-8 mx-auto">
            <strong><h5>Описание:</h5></strong>
            <p>{{category.description}}</p>
            <hr>
        </div>
    </div>
</div>
{% endfor %}
</code>
{% endblock %}

homework23/store/game_store/templates/category/category_games.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{category}}{% endblock %}
{% block content %}
<code>
{% for game in games %}
    <div class="container text-center my-5">
        <h1 class="fw-light">Жанр: {{category.title}}</h1><br>
        <div class="row">
            <div class="col-lg-6 col-md-8 mx-auto">
                <img style="width: 500px; height: 600px; object-fit: cover;" src={{game.game_image.url}} alt={{game.name}}/>
                <div>
                    <br>
                    <strong><a href="{% url 'game:game_slug' game_slug=game.slug %}">{{game.name}}</a></strong><br>
                    <hr>
                </div>
                <br>
                <strong><h5>Описание:</h5></strong>
                <p>{{game.description}}</p>
                <hr>
            </div>
        </div>
    </div>
{% endfor %}
</code>
{% endblock %}

homework23/store/game_store/templates/games/game.html
{% extends  'base.html'%}
{% load static %}
{% block title %}{{game.name}}{% endblock %}

{% block content %}
<code>
    <div class="container text-center my-5">
        <h1 class="fw-light">{{game.name}}</h1><br>
        <div class="row">
            <div class="col-lg-6 col-md-8 mx-auto">
                <img style="width: 500px; height: 600px; object-fit: cover;" src={{game.game_image.url}} alt={{game.name}}/>
                <div>
                    <br>
                    <strong>{{game.name}}</strong><br>
                    <strong>Жанры:</strong>
                    {{game.category}}<br>
                    <strong>Цена:</strong>
                    {{game.price}}
                    <strong>руб</strong><hr>
                </div>
                <br>
                <strong><h5>Описание:</h5></strong>
                <p>{{game.description}}</p>
                <hr>
            </div>
        </div>
    </div>
</code>
{% endblock %}

homework23/store/game_store/templates/games/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Games{% endblock %}

{% block content %}
<code>
    {% for game in games %}
            <img style="width: 400px; height: 400px; object-fit: cover;" src={{game.game_image.url}} alt="Name" />
            <br><br>
            <li><a href="{% url 'game:game_slug' game_slug=game.slug %}">{{game.name}}</a></li>
            <li>Жанр: {{game.category}}</li>
            <li>Цена: {{game.price}} руб</li>
            <li>Дата выхода: {{game.release_date}}</li>
            <hr>
    {% endfor %}
</code>
{% endblock %}